<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerIVb01sU\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerIVb01sU/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerIVb01sU.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerIVb01sU\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerIVb01sU\App_KernelDevDebugContainer([
    'container.build_hash' => 'IVb01sU',
    'container.build_id' => '2b8cc26e',
    'container.build_time' => 1741359537,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerIVb01sU');
